FROM python:3.7-bullseye

RUN apt update
RUN apt install -y ffmpeg

ADD "https://github.com/ZanyMonk/beatbot.git" skipcache
RUN git clone https://github.com/ZanyMonk/beatbot.git /opt/beatbot
WORKDIR /opt/beatbot

RUN pip install -r requirements.txt

COPY .env .env

CMD ["python", "beatbot.py"]

